src/com/product/model/ProductDAO_Interface.java
package com.product.model;
import java.util.*;
public interface ProductDAO_Interface {
	public void insert(ProductVO productVO);
	public void update(ProductVO productVO);
	public void delete(Integer prono);
	public ProductVO findByPrimaryKey(Integer prono);
	public List<ProductVO> getAll();
	//萬用複合查詢(傳入參數型態Map，回傳List)
	public List<ProductVO> getAll(Map<String, String[]> map);
	public void updateByPrimaryKey(ProductVO productVO);
	public void updateStatusByPrimaryKey(ProductVO productVO);
}

src/com/product/model/ProductService.java
package com.product.model;
import java.sql.Connection;
import java.util.*;
public class ProductService {
	private ProductDAO_Interface dao;
	public ProductService(){
		dao = new ProductDAO();
	}
	public ProductVO addProduct(String productname, String category, Integer price, byte[] image1, byte[] image2, byte[] image3, Integer quantity, Integer minimumquantity, Integer status, String keyword, String relatedProducts, Integer priority, Double discount, Integer score, String description){
		ProductVO productVO = new ProductVO();		
		productVO.setProductname(productname);
		productVO.setCategory(category);
		productVO.setPrice(price);
		productVO.setImage1(image1);
		productVO.setImage2(image2);
		productVO.setImage3(image3);
		productVO.setQuantity(quantity);
		productVO.setMinimumquantity(minimumquantity);
		productVO.setStatus(status);
		productVO.setKeyword(keyword);		
		productVO.setRelatedProducts(relatedProducts);
		productVO.setPriority(priority);
		productVO.setDiscount(discount);
		productVO.setScore(score);
		productVO.setDescription(description);
		dao.insert(productVO);
		return productVO;
	}
	public ProductVO updateProduct(Integer prono, String productname, String category, Integer price, byte[] image1, byte[] image2, byte[] image3, Integer quantity, Integer minimumquantity, Integer status, String keyword, String relatedProducts, Integer priority, Double discount, Integer score, String description){
		ProductVO productVO = new ProductVO();
		productVO.setProno(prono);
		productVO.setProductname(productname);
		productVO.setCategory(category);
		productVO.setPrice(price);
		productVO.setImage1(image1);
		productVO.setImage2(image2);
		productVO.setImage3(image3);
		productVO.setQuantity(quantity);
		productVO.setMinimumquantity(minimumquantity);
		productVO.setStatus(status);
		productVO.setKeyword(keyword);
		productVO.setRelatedProducts(relatedProducts);
		productVO.setPriority(priority);
		productVO.setDiscount(discount);
		productVO.setScore(score);
		productVO.setDescription(description);
		dao.update(productVO);
		return productVO;
	}
	
	public ProductVO updateByPrimaryKey(Integer prono, Integer quantity){
		ProductVO productVO = new ProductVO();

		productVO.setProno(prono);
		productVO.setQuantity(quantity);
		dao.updateByPrimaryKey(productVO);
		return productVO;
	}
	
	public ProductVO updateStatusByPrimaryKey(Integer prono, Integer status){
		ProductVO productVO = new ProductVO();

		productVO.setProno(prono);
		productVO.setStatus(status);
		dao.updateStatusByPrimaryKey(productVO);
		return productVO;
	}
	
	public List<ProductVO> getAll(){
		return dao.getAll();
	}
	
	public List<ProductVO> getAll(Map<String, String[]> map){
		return dao.getAll(map);
	}
	
	public ProductVO getOneProduct(Integer prono){
		return dao.findByPrimaryKey(prono);
	}
	
	public void deleteProduct(Integer prono){
		dao.delete(prono);
	}
}

src/com/product/model/ProductVO.java
package com.product.model;
import java.sql.Blob;
import java.sql.Date;

public class ProductVO implements java.io.Serializable{
	private Integer prono;
	private String productname; //can null
	private String category; //can null
	private Integer price; //can null
	private byte[] image1; //can null
	private byte[] image2; //can null
	private byte[] image3; //can null
	private Integer quantity;
	private Integer minimumquantity;
	private Integer status;
	private String keyword; //can null	
	private String relatedProducts; //can null
	private Integer priority;
	private Double discount;
	private Integer score;
	private String description;
	public Integer getProno() {
		return prono;
	}
	public void setProno(Integer prono) {
		this.prono = prono;
	}
	public String getProductname() {
		return productname;
	}
	public void setProductname(String productname) {
		this.productname = productname;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Integer getPrice() {
		return price;
	}
	public void setPrice(Integer price) {
		this.price = price;
	}
	public byte[] getImage1() {
		return image1;
	}
	public void setImage1(byte[] image1) {
		this.image1 = image1;
	}
	public byte[] getImage2() {
		return image2;
	}
	public void setImage2(byte[] image2) {
		this.image2 = image2;
	}
	public byte[] getImage3() {
		return image3;
	}
	public void setImage3(byte[] image3) {
		this.image3 = image3;
	}
	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public Integer getMinimumquantity() {
		return minimumquantity;
	}
	public void setMinimumquantity(Integer minimumquantity) {
		this.minimumquantity = minimumquantity;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public String getKeyword() {
		return keyword;
	}
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}
	public String getRelatedProducts() {
		return relatedProducts;
	}
	public void setRelatedProducts(String relatedProducts) {
		this.relatedProducts = relatedProducts;
	}
	public Integer getPriority() {
		return priority;
	}
	public void setPriority(Integer priority) {
		this.priority = priority;
	}
	public Double getDiscount() {
		return discount;
	}
	public void setDiscount(Double discount) {
		this.discount = discount;
	}
	public Integer getScore() {
		return score;
	}
	public void setScore(Integer score) {
		this.score = score;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	
	
	
}

src/com/product/controller/ProductServlet.java
package com.product.controller;

import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.oreilly.servlet.MultipartRequest;
import com.product.model.ProductService;
import com.product.model.ProductVO;

public class ProductServlet extends HttpServlet {
	String folderPath;

	public void init() throws ServletException {
		String folderName = getInitParameter("createPictureFolder").toString();
		folderPath = (getServletContext().getRealPath(folderName)).toString();
		File imgDir = new File(folderPath);
		if (!imgDir.exists()) {
			imgDir.mkdirs();
			log("資料夾:" + folderName + "初始化完成!");
		}
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		doPost(request, response);
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		request.setCharacterEncoding("UTF-8");
		// String action = request.getParameter("action");
		MultipartRequest multi = null;
		String contentType = request.getContentType();
		String action = null;
		/*
		 * 檢查表單送進來的contentType是否為multipart/form-data
		 * 如果是，則使用MultipartRequest處裡參數。否則直接使用request.getParameter() 處理參數。
		 */
		if ("listItem".equals(request.getParameter("action"))) {
			action = request.getParameter("action");
			String pageFrom = request.getParameter("pageFrom");
			request.setAttribute("pageFrom", pageFrom);
		} else {
			if (contentType != null
					&& contentType.startsWith("multipart/form-data")) {
				multi = new MultipartRequest(request, folderPath,
						10 * 1024 * 1024, "UTF-8");
				action = multi.getParameter("action");
			} else {
				action = request.getParameter("action");
			}
		}

		if ("getOne_For_Display".equals(action) || "listItem".equals(action)) { // 來自select_page.jsp的請求
			List<String> errorMsgs = new LinkedList<String>();
			request.setAttribute("errorMsgs", errorMsgs);

			try {
				// 接收請求參數
				Integer prono = new Integer(request.getParameter("prono"));
				// String url = null;
				if (prono == null) {
					errorMsgs.add("請輸入產品編號");
				}
				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = request
							.getRequestDispatcher("/backend/PRODUCT/select_page.jsp");
					failureView.forward(request, response);
					return;
				}

				// Integer prono = null;
				try {
					// prono = new String.(str);
				} catch (Exception e) {
					errorMsgs.add("產品編號格式不正確");
				}

				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = request
							.getRequestDispatcher("/backend/PRODUCT/select_page.jsp");
					failureView.forward(request, response);
					return;
				}
				// 開始查詢商品資料
				ProductService proSvc = new ProductService();
				ProductVO productVO = proSvc.getOneProduct(prono);
				// String relatedProducts = productVO.getRelatedProducts();
				// String relatedProducts_ary [] = relatedProducts.split(",");
				//
				// if(relatedProducts!=null){
				// int i = 0;
				// for(String token : relatedProducts_ary){
				// i+=1;
				// request.setAttribute("relatedProducts"+i, token);
				// }//取出相關商品編號
				// request.setAttribute("relatedProducts", relatedProducts);
				// }else{
				// request.setAttribute("relatedProducts", null);
				// }
				if (productVO == null) {
					errorMsgs.add("查無資料");
				}
				// 將錯誤訊息轉交予select_page.jsp
				if (!errorMsgs.isEmpty()) {
					RequestDispatcher failureView = request
							.getRequestDispatcher("/backend/PRODUCT/select_page.jsp");
					failureView.forward(request, response);
					return;
				}

				// 查詢完成，將結果轉交予listOneProduct.jsp
				request.setAttribute("productVO", productVO);// 因查詢結果包入productVO物件，自資料庫productVO物件存入request
				String url = null;
				if ("getOne_For_Display".equals(action)) {
					url = "/backend/PRODUCT/listOneProduct.jsp";
				} else if ("listItem".equals(action)) {
					url = "/frontend/ORDERITEM/item.jsp";
				}
				RequestDispatcher successView = request
						.getRequestDispatcher(url);
				successView.forward(request, response);

				// 以下處裡其他可能錯誤
			} catch (Exception e) {
				String url = null;
				if ("getOne_For_Display".equals(action)) {
					url = "/backend/PRODUCT/listOneProduct.jsp";
				} else if ("listItem".equals(action)) {
					url = "/frontend/ORDERITEM/item.jsp";
				}
				errorMsgs.add("無法取得資料:" + e.getMessage());
				RequestDispatcher failureView = request
						.getRequestDispatcher(url);
				failureView.forward(request, response);
			}
		}

		// 來自listAllProduct.jsp 或 /PRODUCTITEM/listAllProductItem.jsp的請求
		if ("getOne_For_Update".equals(action)) {
			List<String> errorMsgs = new LinkedList<String>();
			request.setAttribute("errorMsgs", errorMsgs);

			String requestURL = request.getParameter("requestURL");

			try {
				// 接收請求參數
				Integer prono = new Integer(request.getParameter("prono"));

				// 開始查詢資料
				ProductService proSvc = new ProductService();
				ProductVO productVO = proSvc.getOneProduct(prono);

				// 查詢完畢，轉交查詢結果
				request.setAttribute("productVO", productVO);
				String url = "/backend/PRODUCT/update_product_input.jsp";
				RequestDispatcher successView = request
						.getRequestDispatcher(url);
				successView.forward(request, response);
				// 其他可能的錯誤處裡
			} catch (Exception e) {
				errorMsgs.add("修改資料取出時失敗" + e.getMessage());
				RequestDispatcher failureView = request
						.getRequestDispatcher(requestURL);
				failureView.forward(request, response);
			}
		}
		if ("update".equals(action)) {
			List<String> errorMsgs = new LinkedList<String>();
			request.setAttribute("errorMsgs", errorMsgs);
			// MultipartRequest multi = new MultipartRequest(request,
			// folderPath, 10*1024*1024, "Big5");
			String requestURL = multi.getParameter("requestURL");
			ProductService proSvc = new ProductService();
			try {
				Integer prono = new Integer(multi.getParameter("prono"));
				String productname = multi.getParameter("productname").trim();
				String category = multi.getParameter("category").trim();
				Integer price = new Integer(multi.getParameter("price").trim());

				File file1 = multi.getFile("image1");
				File file2 = multi.getFile("image2");
				File file3 = multi.getFile("image3");
				byte[] image1;
				byte[] image2;
				byte[] image3;
				if (file1 == null) {
					ProductVO productVO = proSvc.getOneProduct(prono);
					image1 = productVO.getImage1();
				} else {
					FileInputStream fis = new FileInputStream(file1);
					int leng = fis.available();
					image1 = new byte[leng];
					fis.read(image1);
					fis.close();
				}
				if (file2 == null) {
					ProductVO productVO = proSvc.getOneProduct(prono);
					image2 = productVO.getImage2();
				} else {
					FileInputStream fis = new FileInputStream(file2);
					int leng = fis.available();
					image2 = new byte[leng];
					fis.read(image2);
					fis.close();
				}
				if (file3 == null) {
					ProductVO productVO = proSvc.getOneProduct(prono);
					image3 = productVO.getImage3();
				} else {
					FileInputStream fis = new FileInputStream(file3);
					int leng = fis.available();
					image3 = new byte[leng];
					fis.read(image3);
					fis.close();
				}
				Integer quantity = null;
				try {
					quantity = new Integer(multi.getParameter("quantity")
							.trim());
				} catch (NumberFormatException e) {
					quantity = 0;
					errorMsgs.add("商品數量請填寫數字");
				}
				Integer minimumquantity = null;
				try {
					minimumquantity = new Integer(multi.getParameter(
							"minimumquantity").trim());
				} catch (NumberFormatException e) {
					minimumquantity = 0;
					errorMsgs.add("商品最低數量請填寫數字");
				}

				Integer status = new Integer(multi.getParameter("status"));
				String keyword = multi.getParameter("keyword").trim();
				String description = multi.getParameter("description");
				String relatedProducts1 = multi
						.getParameter("relatedProducts1").trim();
				String relatedProducts2 = multi
						.getParameter("relatedProducts2").trim();
				String relatedProducts3 = multi
						.getParameter("relatedProducts3").trim();
				String relatedProducts = relatedProducts1 + ","
						+ relatedProducts2 + "," + relatedProducts3;
				Integer priority = new Integer(multi.getParameter("priority"));
				Double discount = null;
				try {
					discount = new Double(multi.getParameter("discount").trim());
				} catch (NumberFormatException e) {
					discount = 1.0;
					errorMsgs.add("商品折扣數請填寫數字");
				}
				Integer score = null;
				try {
					score = new Integer(multi.getParameter("score").trim());
				} catch (NumberFormatException e) {
					errorMsgs.add("商品評分請填寫數字");
				}
				String ordno = multi.getParameter("ordno");

				ProductVO productVO = new ProductVO();
				productVO.setProno(prono);
				productVO.setProductname(productname);
				productVO.setCategory(category);
				productVO.setPrice(price);
				productVO.setImage1(image1);
				productVO.setImage2(image2);
				productVO.setImage3(image3);
				productVO.setQuantity(quantity);
				productVO.setMinimumquantity(minimumquantity);
				productVO.setStatus(status);
				productVO.setKeyword(keyword);
				productVO.setRelatedProducts(relatedProducts);
				productVO.setPriority(priority);
				productVO.setDiscount(discount);
				productVO.setScore(score);
				productVO.setDescription(description);
				if (!errorMsgs.isEmpty()) {
					System.out.println("A");
					request.setAttribute("productVO", productVO);
					RequestDispatcher failureView = request
							.getRequestDispatcher("/backend/PRODUCT/update_product_input.jsp");
					failureView.forward(request, response);
					return;
				}
				// 開始修改資料

WebContent/backend/PRODUCT/addProduct.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="BIG5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.product.model.*"%>
<%@ taglib prefix="sql" uri="http://java.sun.com/jsp/jstl/sql" %>

<%@ page import="java.util.*"%>

<%@ page import="com.pow.model.*"%>
<jsp:useBean id="powSvc" scope="page" class="com.pow.model.PowService" />
<%
ProductVO productVO = (ProductVO) request.getAttribute("productVO");
System.out.println("來自addProduct.jsp 的  productVO="+productVO);
PowVO powVO = powSvc.getOnePowByPKs((Integer)session.getAttribute("empNo"), 4005);
List<PowVO> list = (List<PowVO>)session.getAttribute("list");
%>
<html>
<head>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/style.css">
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.11.0.min.js"></script>
<script src="<%=request.getContextPath()%>/menu.js"></script>	
<title>新增商品</title>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
	window.onload = function(){
		CKEDITOR.replace( 'description' ,{toolbar: 'Full' , skin :  'moono' });
	}
	function test() {  
	    var editor_data = CKEDITOR.instances.content.getData();  
	    if (editor_data== null  || editor_data== "" ){  
	        alert( "請填寫商品簡介內容" );  
	        return  false ;  
	    }  
	}  
</script>
</head>
<body>
	<%@ include file="/menu1.jsp" %> 

<c:if test="<%=list.contains(powVO)%>"> 
<b><h1>新增商品</h1></b>
<c:if test="${not empty errorMsgs}">
	<font color='red'>請修正以下錯誤
	<ul>
		<c:forEach var="message" items="${errorMsgs}">
			<li>${message}</li>
		</c:forEach>
	</ul>
	</font>
</c:if>
<sql:setDataSource dataSource="jdbc/TestDB" var="relatedProducts" scope="application"/>
	<sql:query var="rs" dataSource="${relatedProducts}">
		SELECT * FROM product
	</sql:query>
<form method="post" action="product.do" enctype="multipart/form-data">
	<table>
		<tr>
			<td>商品名稱:</td>
			<td align="left">
				<input type="text" name="productname" size="45">
			</td>
		</tr>
		<tr>
			<td>商品分類:</td>
			<td>
				<select name="category">
					<option value="">--請選擇商品分類--
					<option value="狗飼料">狗飼料
					<option value="狗玩具">狗玩具
					<option value="狗衣服">狗衣服
					<option value="狗藥品">狗藥品
					<option value="貓飼料">貓飼料
					<option value="貓玩具">貓玩具
					<option value="貓衣服">貓衣服
					<option value="貓藥品">貓藥品
					<option value="其他清潔用品">其他清潔用品
				</select>
			</td>
		</tr>
		<tr>
			<td>售價:</td>
			<td><input type="text" name="price" size="45" value="<%=(productVO==null)?"":productVO.getPrice()%>"></td>
		</tr>
		<tr><td>商品圖片:</td>
			<td><input type="file" name="image1"><input type="file" name="image2"><input type="file" name="image3"></td>
		</tr>		
		<tr>
			<td>商品數量:</td>
			<td><input type="text" name="quantity" size="45" value="<%=(productVO==null)?"":productVO.getQuantity()%>"></td>
		</tr>
		<tr>
			<td>安全庫存量:</td>
			<td><input type="text" name="minimumquantity" size="45" value="<%=(productVO==null)?"":productVO.getMinimumquantity()%>"></td>
		</tr>
		<tr>
			<td>商品狀態:</td>
			<td>
				<select name="status">
					<option value="">--請選擇商品狀態--
					<option value="0">未上架
					<option value="1">上架中
				</select>
			</td>
		</tr>
		<tr>
			<td>商品關鍵字:</td>
			<td><textarea cols="80" name="keyword" rows="1"><%=(productVO==null)?"":productVO.getKeyword()%></textarea></td>
		</tr>
		<tr>
			<td>商品簡介:</td>
			<td><textarea class="ckeditor" id="description" cols="80" name="description" rows="10"><%=(productVO==null)?"":productVO.getDescription()%></textarea>
			<input type="hidden" name="relatedProducts1" value="">
			<input type="hidden" name="relatedProducts2" value="">
			<input type="hidden" name="relatedProducts3" value="">
			</td>
		</tr>
		<tr>
			<td>折扣數:<input name="score" value="0" type="hidden"></td>
			<td><input type="text" name="discount" size="45" value="1.0">(1.0表示不打折)
				<input type="hidden" name="priority" size="45" value="1"></td>
		</tr>
	</table>
		<input name="action" value="insert" type="hidden">
		<input name="submit" value="新增商品" type="submit" onclick="test()">
	</form>
	</c:if>
	
		<%@ include file="/menu2.jsp" %> 
</body>
</html>

WebContent/backend/PRODUCT/select_page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="BIG5"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="sql" uri="http://java.sun.com/jsp/jstl/sql" %>
<%@ page import="java.util.*"%>
<%@ page import="com.product.model.*"%>  


<%@ page import="com.pow.model.*"%>
<jsp:useBean id="powSvc" scope="page" class="com.pow.model.PowService" />
<%
PowVO powVO = powSvc.getOnePowByPKs((Integer)session.getAttribute("empNo"), 4005);
List<PowVO> listPower = (List<PowVO>)session.getAttribute("list");
%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=BIG5">
<title>商品查詢</title>
<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/style.css">
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-1.11.0.min.js"></script>
<script src="<%=request.getContextPath()%>/menu.js"></script>	
</head>
<body>
<%@ include file="/menu1.jsp" %> 

<c:if test="<%=listPower.contains(powVO)%>"> 
<b><h1>查詢商品</h1></b>
<%--錯誤表列 --%>
<c:if test="${not empty errorMsgs}">
	<font color='red'>請修正以下錯誤:
	<ul>
	<c:forEach var="message" items="${errorMsgs}">
		<li>${message}</li>
	</c:forEach>
	</ul>
	</font>
</c:if>

<!-- <ul>	 -->
<!-- 	<b>商品管理</b> -->
<%-- 	<li><a href='<%=request.getContextPath()%>/backend/PRODUCT/listAllProduct.jsp'>檢視所有商品</a></li>	 --%>
<%-- 	<li><a href='<%=request.getContextPath()%>/backend/PRODUCT/addProduct.jsp'>新增商品</a></li> --%>

<!-- <ul> -->
	<b>商品管理</b>
	<li><a href='<%=request.getContextPath()%>/backend/PRODUCT/addProduct.jsp'>新增商品</a></li>
	<li><a href='<%=request.getContextPath()%>/backend/PRODUCT/listAllProduct.jsp'>檢視所有商品</a></li>

	<li>
		<form method="post" action="<%=request.getContextPath()%>/backend/PRODUCT/product.do">
			<b>請輸入商品編號:</b>
			<input type="text" name="prono">
			<input type="submit" value="查詢商品">
			<input type="hidden" name="action" value="getOne_For_Display">
		</form>
	</li>
	
	<jsp:useBean id="proSvc" scope="page" class="com.product.model.ProductService"/>
	<li>
		<form method="post" action="<%=request.getContextPath()%>/backend/PRODUCT/product.do">
			<b>請選擇商品編號:</b>
			<select size="1" name="prono">
				<c:forEach var="productVO" items="${proSvc.all}">
					<option value="${productVO.prono}">${productVO.prono}
				</c:forEach>
			</select>
			<input type="submit" value="查詢商品">
			<input type="hidden" name="action" value="getOne_For_Display">
		</form>
	</li>
	<li>
	<sql:setDataSource dataSource="jdbc/TestDB" var="productCategory" scope="application"/>
	<sql:query var="rs" dataSource="${productCategory}">
		SELECT DISTINCT category FROM product
	</sql:query>
		<form method="post" action="<%=request.getContextPath()%>/backend/PRODUCT/product.do" name="form1">
		<b><font color=blue>請設定查詢條件</font></b><br>
		<b>商品編號:</b>
		<input type="text" name="prono" value=""><br>
		<b>商品名稱:</b>
		<input type="text" name="productname" value=""><br>
		<b>商品分類:</b>

		<select name="category">
			<option value="">--請選擇商品分類--
			<c:forEach var="row" items="${rs.rows}" varStatus="status">
				<option value='<c:out value="${row.category}"/>'><c:out value="${row.category}"/>
			</c:forEach>
		</select><br>
		<b>商品狀態:</b>
		<select name="status">
			<option value="">--請選擇商品狀態--
			<option value="0">未上架
			<option value="1">上架中
			<option value="2">已下架
		</select><br>
		<b>商品關鍵字:</b>
		<input type="text" name="keyword" value="">
		<input name="action" value="listPorduct_ByCompositeQuery" type="hidden"><br> 
		<input value="查詢商品" type="submit">
		<input value="重設條件" type="reset">
	</form>
	</li>
	
</ul>

</c:if>
<%@ include file="/menu2.jsp" %> 

</body>
</html>